
services:
  memgraph:
    image: memgraph/memgraph:latest
    container_name: karyon_memgraph
    ports:
      - "7687:7687"
    environment:
      - MEMGRAPH_TELEMETRY_ENABLED=false
    command: ["--log-level=WARNING"]
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_logs:/var/log/memgraph

  xtdb:
    image: ghcr.io/xtdb/xtdb:latest
    container_name: karyon_xtdb
    ports:
      - "3000:3000"
    volumes:
      - xtdb_data:/var/lib/xtdb

  nats:
    image: nats:latest
    container_name: karyon_nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  memgraph_data:
  memgraph_logs:
  xtdb_data:
