import type { AgentHandler } from '../runtime-types.ts';

interface ArchitectInputs {
	objectiveId: string | null;
	leaseToken: string | null;
}

interface ArchitectResult extends ArchitectInputs {
	knowledgeSlug: string | null;
}

export const architectHandler: AgentHandler<ArchitectInputs, ArchitectResult> = {
	kind: 'architect',
	async resolveInputs(context) {
		const payload = context.trigger.message ? JSON.parse(context.trigger.message.payloadJson) as Record<string, unknown> : null;
		if (typeof payload?.objectiveId === 'string') {
			return {
				objectiveId: payload.objectiveId,
				leaseToken: null,
			};
		}

		const picked = await context.sdk.pick({
			model: 'objective',
			leaseSeconds: context.agent.execution.leaseSeconds,
			workerId: `${context.agent.slug}-${context.runId}`,
		});
		return {
			objectiveId: (picked.payload.item as { id?: string } | null)?.id ?? null,
			leaseToken: picked.payload.leaseToken,
		};
	},
	async execute(context, inputs) {
		if (!inputs.objectiveId) {
			return {
				...inputs,
				knowledgeSlug: null,
			};
		}

		const knowledgeSlug = `architecture/agent-mvp/${inputs.objectiveId}-${context.runId}`;
		await context.sdk.create({
			model: 'knowledge',
			data: {
				slug: knowledgeSlug,
				title: `Architecture update for ${inputs.objectiveId}`,
				body: [
					'# Architecture Update',
					'',
					`Objective: ${inputs.objectiveId}`,
					`Run: ${context.runId}`,
					'',
					'This knowledge entry was generated by the MVP architecture handler.',
				].join('\n'),
				tags: ['agent', 'architecture', 'mvp'],
				branchPrefix: context.agent.execution.branchPrefix,
			},
		});

		return {
			...inputs,
			knowledgeSlug,
		};
	},
	async emitOutputs(context, result) {
		if (!result.objectiveId || !result.knowledgeSlug) {
			return {
				status: 'waiting',
				summary: 'Architect found no objective to process.',
			};
		}

		await context.sdk.createMessage({
			type: 'architecture_updated',
			payload: {
				objectiveId: result.objectiveId,
				knowledgeId: result.knowledgeSlug,
				architectRunId: context.runId,
			},
		});
		if (result.leaseToken) {
			await context.sdk.releaseLease({
				model: 'objective',
				itemKey: result.objectiveId,
				leaseToken: result.leaseToken,
			});
		}
		return {
			status: 'completed',
			summary: `Architect created knowledge ${result.knowledgeSlug}.`,
		};
	},
};
