import type { AgentHandler } from '../runtime-types.ts';
import {
	parseAgentMessagePayload,
	serializeAgentMessagePayload,
} from '../contracts/messages.ts';

interface ResearcherInputs {
	questionId: string | null;
	reason: string | null;
}

interface ResearcherResult extends ResearcherInputs {
	knowledgeSlug: string | null;
}

export const researcherHandler: AgentHandler<ResearcherInputs, ResearcherResult> = {
	kind: 'researcher',
	async resolveInputs(context) {
		if (!context.trigger.message) {
			throw new Error('Researcher requires a claimed message trigger.');
		}
		const payload = parseAgentMessagePayload(
			'question_priority_updated',
			context.trigger.message.payloadJson,
		);
		return {
			questionId: payload.questionId,
			reason: payload.reason,
		};
	},
	async execute(context, inputs) {
		if (!inputs.questionId) {
			return {
				...inputs,
				knowledgeSlug: null,
			};
		}

		const knowledgeSlug = `research/agent-mvp/${inputs.questionId}-${context.runId}`;
		await context.sdk.create({
			model: 'knowledge',
			data: {
				slug: knowledgeSlug,
				title: `Research update for ${inputs.questionId}`,
				body: [
					'# Research Update',
					'',
					`Question: ${inputs.questionId}`,
					`Reason: ${inputs.reason ?? 'not provided'}`,
					`Run: ${context.runId}`,
					'',
					'This knowledge entry was generated by the MVP researcher handler.',
				].join('\n'),
				tags: ['agent', 'research', 'mvp'],
				branchPrefix: context.agent.execution.branchPrefix,
			},
		});
		await context.sdk.create({
			model: 'note',
			data: {
				slug: `research-note-${context.runId}`,
				title: `Research note for ${inputs.questionId}`,
				description: `Research note captured for ${inputs.questionId}.`,
				date: new Date().toISOString(),
				status: 'in progress',
				tags: ['agent', 'research'],
				summary: `A research note was created for ${inputs.questionId}.`,
				author: context.agent.slug,
				body: `Research notes for ${inputs.questionId}.`,
				branchPrefix: context.agent.execution.branchPrefix,
			},
		});

		return {
			...inputs,
			knowledgeSlug,
		};
	},
	async emitOutputs(context, result) {
		if (!result.questionId) {
			return {
				status: 'waiting',
				summary: 'Researcher found no question to process.',
			};
		}

		await context.sdk.createMessage({
			type: 'research_started',
			payload: serializeAgentMessagePayload('research_started', {
				questionId: result.questionId,
				researcherRunId: context.runId,
			}),
		});
		await context.sdk.createMessage({
			type: 'research_completed',
			payload: serializeAgentMessagePayload('research_completed', {
				questionId: result.questionId,
				knowledgeId: result.knowledgeSlug,
				researcherRunId: context.runId,
			}),
		});
		return {
			status: 'completed',
			summary: `Researcher created knowledge ${result.knowledgeSlug}.`,
		};
	},
};
