defmodule NervousSystem.Protos do
  @moduledoc """
  Manual implementation of Protobuf-compatible modules.
  NOTE: In production, these should be generated by protox or protobuf-elixir
  once the `protoc` binary is available in the environment.
  """

  defmodule PredictionError do
    def encode(msg) do
      # Mocking binary encoding for now using JSON for transparency in logs
      Jason.encode!(msg)
    end

    def decode!(binary) do
      Jason.decode!(binary)
    end
    
    def new(fields), do: Map.merge(%{type: "", message: "", timestamp: 0, metadata: %{}, cell_id: ""}, Map.new(fields))
  end

  defmodule MetabolicSpike do
    def encode(msg) do
      Jason.encode!(msg)
    end

    def decode!(binary), do: Jason.decode!(binary)
    def decode(binary), do: Jason.decode(binary)

    def new(fields), do: Map.merge(%{metric_type: "", value: 0.0, threshold: 0.0, timestamp: 0, severity: ""}, Map.new(fields))
  end
end
